version: "3"
services:
    proxy:
        image: caddy
        container_name: subsistema2_proxy
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
        ports:
            - 80:80
        depends_on:
            - backend
    backend:
        image: stoplight/prism:4
        container_name: subsistema2_mock
        command: mock --cors -h 0.0.0.0 "/aos/subsistema2.yaml"
        ports:
          - 4010:4010
        volumes:
            - ./Trabajo:/aos:ro
    frontend:
        image: swaggerapi/swagger-ui
        container_name: subsistema2_ui
        ports:
            - 8001:8080
        environment:
            SWAGGER_JSON: /aos/subsistema2.yaml
        volumes:
            - ./Trabajo:/aos:ro
